# Data Mining Project - Phase 4 - Ehsan Espandar - 99442011

In [2]:
import pandas as pd

In [3]:
data_packet = pd.read_csv('housing.csv')

In [4]:
from sklearn.model_selection import train_test_split

X = data_packet.drop('median_house_value', axis=1) 
y = data_packet['median_house_value'] 


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2021)

print(len(X_train),len(y_train))
print(len(X_test),len(y_test))

16512 16512
4128 4128

# Phase 3

## Question 1

In [5]:
import copy
import pandas as pd

# Assuming X_train and y_train are your feature and target DataFrames respectively
X_train_copy = copy.copy(X_train)
y_train_copy = copy.copy(y_train)

# Concatenate X_train and y_train along columns axis
data = pd.concat([X_train_copy, y_train_copy], axis=1)


print(data)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2782     -114.66     32.74                17.0       1388.0           386.0
8513     -118.31     33.89                35.0       2144.0           423.0
2163     -119.82     36.77                41.0       1441.0           274.0
5232     -118.24     33.94                42.0        380.0           106.0
9766     -121.66     36.37                 9.0       1580.0           287.0
...          ...       ...                 ...          ...             ...
16347    -121.35     38.02                16.0       1665.0           311.0
20318    -119.15     34.20                25.0       3445.0           898.0
2669     -115.51     33.24                32.0       1995.0           523.0
17536    -121.88     37.35                49.0       1728.0           350.0
6201     -117.89     34.08                25.0       2115.0           489.0

       population  households  median_income ocean_proximity  \
2782        775.0       320.0         1.2049          INLAND
8513       1192.0       417.0         4.1458       <1H OCEAN
2163        646.0       296.0         3.0568          INLAND
5232        411.0       100.0         0.9705       <1H OCEAN
9766        465.0       208.0         6.1668       <1H OCEAN
...           ...         ...            ...             ...
16347      1301.0       259.0         2.8403          INLAND
20318      5558.0       894.0         3.0972      NEAR OCEAN
2669       1069.0       410.0         1.6552          INLAND
17536      1146.0       391.0         3.5781       <1H OCEAN
6201       1107.0       477.0         3.1949       <1H OCEAN

       median_house_value
2782              44000.0
8513             231500.0
2163              71300.0
5232              90000.0
9766             405800.0
...                   ...
16347            132300.0
20318            169300.0
2669              43300.0
17536            193000.0
6201             207400.0

[16512 rows x 10 columns]

## Question 2

In [6]:
label = data["median_house_value"].copy()

data_without_label = data.drop("median_house_value", axis=1)

# Display the copied feature and the dataset without "ocean_proximity"
print("Copied label 'median_house_value':\n", label)
print("\nDataset without 'median_house_value':\n", data_without_label)

Copied label 'median_house_value':
 2782      44000.0
8513     231500.0
2163      71300.0
5232      90000.0
9766     405800.0
           ...
16347    132300.0
20318    169300.0
2669      43300.0
17536    193000.0
6201     207400.0
Name: median_house_value, Length: 16512, dtype: float64

Dataset without 'median_house_value':
        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2782     -114.66     32.74                17.0       1388.0           386.0
8513     -118.31     33.89                35.0       2144.0           423.0
2163     -119.82     36.77                41.0       1441.0           274.0
5232     -118.24     33.94                42.0        380.0           106.0
9766     -121.66     36.37                 9.0       1580.0           287.0
...          ...       ...                 ...          ...             ...
16347    -121.35     38.02                16.0       1665.0           311.0
20318    -119.15     34.20                25.0       3445.0           898.0
2669     -115.51     33.24                32.0       1995.0           523.0
17536    -121.88     37.35                49.0       1728.0           350.0
6201     -117.89     34.08                25.0       2115.0           489.0

       population  households  median_income ocean_proximity
2782        775.0       320.0         1.2049          INLAND
8513       1192.0       417.0         4.1458       <1H OCEAN
2163        646.0       296.0         3.0568          INLAND
5232        411.0       100.0         0.9705       <1H OCEAN
9766        465.0       208.0         6.1668       <1H OCEAN
...           ...         ...            ...             ...
16347      1301.0       259.0         2.8403          INLAND
20318      5558.0       894.0         3.0972      NEAR OCEAN
2669       1069.0       410.0         1.6552          INLAND
17536      1146.0       391.0         3.5781       <1H OCEAN
6201       1107.0       477.0         3.1949       <1H OCEAN

[16512 rows x 9 columns]

## Question 3

In [7]:
# Create a copy of the "ocean_proximity" feature
ocean_proximity_copy = data_without_label["ocean_proximity"].copy()

# Remove the "ocean_proximity" feature from the original dataset
data_without_ocean_proximity = data_without_label.drop("ocean_proximity", axis=1)

# Display the copied feature and the dataset without "ocean_proximity"
print("Copied feature 'ocean_proximity':\n", ocean_proximity_copy)
print("\nDataset without 'ocean_proximity':\n", data_without_ocean_proximity)

Copied feature 'ocean_proximity':
 2782         INLAND
8513      <1H OCEAN
2163         INLAND
5232      <1H OCEAN
9766      <1H OCEAN
            ...
16347        INLAND
20318    NEAR OCEAN
2669         INLAND
17536     <1H OCEAN
6201      <1H OCEAN
Name: ocean_proximity, Length: 16512, dtype: object

Dataset without 'ocean_proximity':
        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2782     -114.66     32.74                17.0       1388.0           386.0
8513     -118.31     33.89                35.0       2144.0           423.0
2163     -119.82     36.77                41.0       1441.0           274.0
5232     -118.24     33.94                42.0        380.0           106.0
9766     -121.66     36.37                 9.0       1580.0           287.0
...          ...       ...                 ...          ...             ...
16347    -121.35     38.02                16.0       1665.0           311.0
20318    -119.15     34.20                25.0       3445.0           898.0
2669     -115.51     33.24                32.0       1995.0           523.0
17536    -121.88     37.35                49.0       1728.0           350.0
6201     -117.89     34.08                25.0       2115.0           489.0

       population  households  median_income
2782        775.0       320.0         1.2049
8513       1192.0       417.0         4.1458
2163        646.0       296.0         3.0568
5232        411.0       100.0         0.9705
9766        465.0       208.0         6.1668
...           ...         ...            ...
16347      1301.0       259.0         2.8403
20318      5558.0       894.0         3.0972
2669       1069.0       410.0         1.6552
17536      1146.0       391.0         3.5781
6201       1107.0       477.0         3.1949

[16512 rows x 8 columns]

## Question 4 , 5 , 6

In [8]:
from sklearn.impute import SimpleImputer

#As data has a normal distribution and not heavy amount of outliers then the 'mean' strategy is the method we use to normalize the dataset.

# Selecting only numerical features
numerical_features = ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income']

# Creating a SimpleImputer instance with a chosen strategy (e.g., mean)
imputer = SimpleImputer(strategy='mean')

# Fitting the imputer on the data and transforming it to fill missing values
data_without_ocean_proximity[numerical_features] = imputer.fit_transform(data_without_ocean_proximity[numerical_features])

print(data_without_ocean_proximity)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2782     -114.66     32.74                17.0       1388.0           386.0
8513     -118.31     33.89                35.0       2144.0           423.0
2163     -119.82     36.77                41.0       1441.0           274.0
5232     -118.24     33.94                42.0        380.0           106.0
9766     -121.66     36.37                 9.0       1580.0           287.0
...          ...       ...                 ...          ...             ...
16347    -121.35     38.02                16.0       1665.0           311.0
20318    -119.15     34.20                25.0       3445.0           898.0
2669     -115.51     33.24                32.0       1995.0           523.0
17536    -121.88     37.35                49.0       1728.0           350.0
6201     -117.89     34.08                25.0       2115.0           489.0

       population  households  median_income
2782        775.0       320.0         1.2049
8513       1192.0       417.0         4.1458
2163        646.0       296.0         3.0568
5232        411.0       100.0         0.9705
9766        465.0       208.0         6.1668
...           ...         ...            ...
16347      1301.0       259.0         2.8403
20318      5558.0       894.0         3.0972
2669       1069.0       410.0         1.6552
17536      1146.0       391.0         3.5781
6201       1107.0       477.0         3.1949

[16512 rows x 8 columns]

## Question 7

In [14]:
imputed_data_df = pd.DataFrame(data_without_ocean_proximity, columns=numerical_features)
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
rooms_ix,bedrooms_ix,population_ix,household_ix=3,4,5,6

class CombinedAttributesAdder(BaseEstimator,TransformerMixin):
    def fit(self,x,y=None):
        return self
    def transform(self,x,y=None):
        rooms_per_household=x[:,rooms_ix]/x[:,household_ix]
        population_per_household=x[:,population_ix]/x[:,household_ix]
        bedrooms_per_room=x[:,bedrooms_ix]/x[:,rooms_ix]
        return np.c_[x,rooms_per_household,population_per_household,bedrooms_per_room]
        
custom=CombinedAttributesAdder()
data_custom_tr_top=custom.transform(imputed_data_df.values)
data_custom_tr=pd.DataFrame(data_custom_tr_top)
columns=list(imputed_data_df)
columns.append('rooms_per_household')
columns.append('population_per_household')
columns.append('bedrooms_per_room')
data_custom_tr.columns=columns
data_custom_tr.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,rooms_per_household,population_per_household,bedrooms_per_room
0,-114.66,32.74,17.0,1388.0,386.0,775.0,320.0,1.2049,4.337500,2.421875,0.278098
1,-118.31,33.89,35.0,2144.0,423.0,1192.0,417.0,4.1458,5.141487,2.858513,0.197295
2,-119.82,36.77,41.0,1441.0,274.0,646.0,296.0,3.0568,4.868243,2.182432,0.190146
3,-118.24,33.94,42.0,380.0,106.0,411.0,100.0,0.9705,3.800000,4.110000,0.278947
4,-121.66,36.37,9.0,1580.0,287.0,465.0,208.0,6.1668,7.596154,2.235577,0.181646
5,-121.85,37.36,15.0,3148.0,1116.0,3556.0,1037.0,3.0466,3.035680,3.429122,0.354511
6,-122.49,37.79,52.0,2488.0,281.0,805.0,295.0,10.7058,8.433898,2.728814,0.112942
7,-117.87,33.76,6.0,2992.0,1194.0,3800.0,1130.0,2.2460,2.647788,3.362832,0.399064
8,-118.22,33.88,35.0,998.0,313.0,1335.0,311.0,1.6574,3.209003,4.292605,0.313627
9,-122.20,39.15,33.0,1064.0,174.0,434.0,147.0,3.1250,7.238095,2.952381,0.163534

## Question 8

In [17]:
from sklearn.preprocessing import StandardScaler

# Selecting only numerical features
numerical_features = ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'rooms_per_household', 'population_per_household', 'bedrooms_per_room']

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler on the data and transform it to standardize the features
data_custom_tr[numerical_features] = scaler.fit_transform(data_custom_tr[numerical_features])

print(data_custom_tr)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       2.453114 -1.356402           -0.919431    -0.567531       -0.361595
1       0.630571 -0.818013            0.507393    -0.224185       -0.274180
2      -0.123413  0.530301            0.983001    -0.543460       -0.626200
3       0.665524 -0.794605            1.062269    -1.025325       -1.023109
4      -1.042174  0.343035           -1.553576    -0.480332       -0.595487
...          ...       ...                 ...          ...             ...
16507  -0.887383  1.115506           -0.998699    -0.441728       -0.538786
16508   0.211136 -0.672882           -0.285287     0.366678        0.848031
16509   2.028686 -1.122320            0.269589    -0.291855       -0.037925
16510  -1.152026  0.801836            1.617146    -0.413116       -0.446646
16511   0.840288 -0.729061           -0.285287    -0.237356       -0.118252

       population  households  median_income  rooms_per_household  \
0       -0.568757   -0.467793      -1.405487            -0.423899
1       -0.205156   -0.215835       0.147943            -0.113188
2       -0.681238   -0.530133      -0.427284            -0.218787
3       -0.886145   -1.039244      -1.529301            -0.631622
4       -0.839060   -0.758713       1.215468             0.835447
...           ...         ...            ...                  ...
16507   -0.110114   -0.626241      -0.541642             0.384221
16508    3.601757    1.023174      -0.405944            -0.610959
16509   -0.312405   -0.234018      -1.167631            -0.219710
16510   -0.245266   -0.283370      -0.151925            -0.392233
16511   -0.279271   -0.059985      -0.354337            -0.386620

       population_per_household  bedrooms_per_room
0                     -0.060476           0.884580
1                     -0.019373          -0.246127
2                     -0.083016          -0.346166
3                      0.098435           0.896466
4                     -0.078014          -0.465112
...                         ...                ...
16507                  0.184396          -0.393169
16508                  0.296778           0.640672
16509                 -0.043020           0.661490
16510                 -0.012555          -0.172641
16511                 -0.069995           0.228400

[16512 rows x 11 columns]

## Question 9

In [22]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder instance
label_encoder = LabelEncoder()

# Fit and transform the 'ocean_proximity' column
ocean_proximity_copy = label_encoder.fit_transform(ocean_proximity_copy)
print(ocean_proximity_copy)

[1 0 1 ... 1 0 0]

## Question 10

In [24]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import pandas as pd

# Assuming 'ocean_proximity_copy' is your encoded column as a NumPy array
ocean_proximity_copy = ocean_proximity_copy.reshape(-1, 1)  # Reshape to a 2D array

# Create a ColumnTransformer with OneHotEncoder
column_transformer = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],  # Assuming 'ocean_proximity_copy' is the first column
    remainder='passthrough'  # Keep the other columns as is
)

# Fit and transform the specified column using the ColumnTransformer
ocean_proximity_onehot = column_transformer.fit_transform(ocean_proximity_copy)

# Convert the result back to a DataFrame
ocean_proximity_onehot_df = pd.DataFrame(ocean_proximity_onehot)

# Display the resulting DataFrame
print(ocean_proximity_onehot_df)

      ocean_proximity_0
0           (0, 1)\t1.0
1           (0, 0)\t1.0
2           (0, 1)\t1.0
3           (0, 0)\t1.0
4           (0, 0)\t1.0
...                 ...
16507       (0, 1)\t1.0
16508       (0, 4)\t1.0
16509       (0, 1)\t1.0
16510       (0, 0)\t1.0
16511       (0, 0)\t1.0

[16512 rows x 1 columns]

## Question 11

In [30]:
# Assuming 'data_custom_tr' is your original DataFrame and 'ocean_proximity_onehot_df' is the one-hot encoded DataFrame
data_custom_tr = pd.concat([data_custom_tr, ocean_proximity_onehot_df], axis=1)


# Display the resulting DataFrame
print(data_custom_tr)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       2.453114 -1.356402           -0.919431    -0.567531       -0.361595
1       0.630571 -0.818013            0.507393    -0.224185       -0.274180
2      -0.123413  0.530301            0.983001    -0.543460       -0.626200
3       0.665524 -0.794605            1.062269    -1.025325       -1.023109
4      -1.042174  0.343035           -1.553576    -0.480332       -0.595487
...          ...       ...                 ...          ...             ...
16507  -0.887383  1.115506           -0.998699    -0.441728       -0.538786
16508   0.211136 -0.672882           -0.285287     0.366678        0.848031
16509   2.028686 -1.122320            0.269589    -0.291855       -0.037925
16510  -1.152026  0.801836            1.617146    -0.413116       -0.446646
16511   0.840288 -0.729061           -0.285287    -0.237356       -0.118252

       population  households  median_income  rooms_per_household  \
0       -0.568757   -0.467793      -1.405487            -0.423899
1       -0.205156   -0.215835       0.147943            -0.113188
2       -0.681238   -0.530133      -0.427284            -0.218787
3       -0.886145   -1.039244      -1.529301            -0.631622
4       -0.839060   -0.758713       1.215468             0.835447
...           ...         ...            ...                  ...
16507   -0.110114   -0.626241      -0.541642             0.384221
16508    3.601757    1.023174      -0.405944            -0.610959
16509   -0.312405   -0.234018      -1.167631            -0.219710
16510   -0.245266   -0.283370      -0.151925            -0.392233
16511   -0.279271   -0.059985      -0.354337            -0.386620

       population_per_household  bedrooms_per_room ocean_proximity_0
0                     -0.060476           0.884580       (0, 1)\t1.0
1                     -0.019373          -0.246127       (0, 0)\t1.0
2                     -0.083016          -0.346166       (0, 1)\t1.0
3                      0.098435           0.896466       (0, 0)\t1.0
4                     -0.078014          -0.465112       (0, 0)\t1.0
...                         ...                ...               ...
16507                  0.184396          -0.393169       (0, 1)\t1.0
16508                  0.296778           0.640672       (0, 4)\t1.0
16509                 -0.043020           0.661490       (0, 1)\t1.0
16510                 -0.012555          -0.172641       (0, 0)\t1.0
16511                 -0.069995           0.228400       (0, 0)\t1.0

[16512 rows x 12 columns]

### About pipeline it is not totally clear that what we must do please make it clear whenever you have seen my project answer, thank you.